variable "project_name" {
  description = "Project name used for resource names."
  type        = string

  validation {
    condition     = can(regex("^[a-zA-Z0-9-]+$", var.project_name))
    error_message = "project_name may contain only letters, numbers, and hyphens."
  }
}

variable "environment" {
  description = "Environment name, such as dev, stg, or prod."
  type        = string

  validation {
    condition     = can(regex("^[a-zA-Z0-9-]+$", var.environment))
    error_message = "environment may contain only letters, numbers, and hyphens."
  }
}

variable "region" {
  description = "AWS region for regional resources. CloudFront WAF is managed through us-east-1 by the provider alias generated by Terragrunt."
  type        = string
}

variable "corporate_ipv4_cidrs" {
  description = "IPv4 CIDR ranges allowed to access CloudFront."
  type        = list(string)
  default     = []
}

variable "corporate_ipv6_cidrs" {
  description = "IPv6 CIDR ranges allowed to access CloudFront. If empty, CloudFront IPv6 is disabled to avoid IPv6 bypass."
  type        = list(string)
  default     = []
}

variable "origin_verify_header_name" {
  description = "Header name added by CloudFront and required by API Gateway WAF."
  type        = string
  default     = "x-origin-verify"

  validation {
    condition     = can(regex("^[A-Za-z0-9-]+$", var.origin_verify_header_name))
    error_message = "origin_verify_header_name must be a valid simple HTTP header name."
  }
}

variable "origin_verify_secret" {
  description = "High-entropy shared secret added by CloudFront and checked by API Gateway WAF. Pass this from an environment variable or secret store."
  type        = string
  sensitive   = true

  validation {
    condition     = length(var.origin_verify_secret) >= 32 && var.origin_verify_secret != "replace-me-with-at-least-32-random-chars"
    error_message = "origin_verify_secret must be at least 32 characters and must not be the placeholder value."
  }
}

variable "api_stage_name" {
  description = "API Gateway stage name."
  type        = string
  default     = "prod"
}

variable "api_resource_server_identifier" {
  description = "Cognito resource server identifier used to build the custom API scope required by API Gateway."
  type        = string
  default     = "api"

  validation {
    condition     = can(regex("^[A-Za-z0-9._:/-]+$", var.api_resource_server_identifier))
    error_message = "api_resource_server_identifier contains unsupported characters."
  }
}

variable "api_scope_name" {
  description = "Cognito custom scope name required by API Gateway methods."
  type        = string
  default     = "invoke"

  validation {
    condition     = can(regex("^[A-Za-z0-9._-]+$", var.api_scope_name))
    error_message = "api_scope_name may contain letters, numbers, dots, underscores, and hyphens."
  }
}

variable "oauth_standard_scopes" {
  description = "Standard OAuth scopes requested by the SPA through Cognito Hosted UI."
  type        = list(string)
  default     = ["openid", "email", "profile"]
}

variable "enable_waf_managed_rules" {
  description = "Enable AWSManagedRulesCommonRuleSet on CloudFront and API Gateway WAF ACLs. Validate false positives before production use."
  type        = bool
  default     = true
}

variable "cloudfront_rate_limit" {
  description = "Rate-based WAF limit for CloudFront, counted per five-minute window per source IP."
  type        = number
  default     = 2000
}

variable "api_rate_limit" {
  description = "Rate-based WAF limit for API Gateway, counted per five-minute window per source IP."
  type        = number
  default     = 1000
}

variable "cloudfront_origin_facing_ipv4_cidrs_override" {
  description = "Optional override for CloudFront origin-facing IPv4 CIDRs. Leave empty to read AWS ip-ranges.json service=CLOUDFRONT at plan time."
  type        = list(string)
  default     = []
}

variable "cloudfront_origin_facing_ipv6_cidrs_override" {
  description = "Optional override for CloudFront origin-facing IPv6 CIDRs. Leave empty to read AWS ip-ranges.json service=CLOUDFRONT at plan time."
  type        = list(string)
  default     = []
}

variable "tags" {
  description = "Additional tags."
  type        = map(string)
  default     = {}
}
